### ISSUE TITLE
Server Messages

### ISSUE THREAD

**Issue by philkjacobs** [philkjacobs/superlatives#17]
Assuming perfect network conditions and all players are good actors for now.

## Server Send:
After new websocket created, broadcast:
```
msg 
  - 'login'
data
  - game_id = uuid
  - players = list of strings
error
  - none
```
On every gamestate transition, broadcast:
```
msg
  - 'change_state'
data
  - ENUM.STATES.FOO (FOO in write, assign, read)
error
 - None
```

After all gamestates to ASSIGN, to each user:
```
msg
  - 'assign_supers_list'
data
  - supers = list of strings that this user needs to pass out
error
 - none
```
After all gamestates to READ, to each user:
```
msg
  - 'read_supers_list'
data
  - supers = list of strings that this user received.
error
 - none
```
Then delete everything!

## Client Send:
```
Login = ws://localhost:5000?name=foo&game=bar
- game not sent if creating a game
- for now assume all names unique
```
```
msg
  - 'change_state'
data
  - ENUM.STATES.FOO (FOO in write, assign, read)
error
 - None
```
```
msg
  - write_super
data
  - super = the message itself aka most essential to group dynamic
error
  - None
```
```
msg
  - assign_super
data
  - super = the message itself aka most essential to group dynamic
  - receipient = person's name
error
  - None
```
Then solitaire.gif

**Comment by mathewantony31** [comment]
@philkjacobs - when the host taps "Starts game" (changes state to "write" locally) this should broadcast a "write" state to all players. Is this accounted in one of the methods above?

**Comment by philkjacobs** [comment]
I was having that be "change_state" - except I was waiting for everyone to ready up.

I can change that to ignore the call unless the host does it and then swap everyone if that's the case.

**Comment by mathewantony31** [comment]
could we change it to the latter? i.e. swap everyone to `write` if the host sends the `write` call
