### ISSUE TITLE
Use human-readable game IDs

### ISSUE THREAD

**Issue by mathewantony31** [philkjacobs/superlatives#30]
@philkjacobs would it be possible to have game IDs be two sets of three-letter words? i.e. "bob-cat", "pop-dog"?

**Comment by philkjacobs** [comment]
We can make it into a string of words, but it'd need to be longer than two 3 letter words.  There's just not enough complexity if we restrict to that.  Collisions would happen.

There are only 1015 words recognized by scrabble so there's only 1 million possibilities with that setup.

**Comment by mathewantony31** [comment]
can we do three sets of three letter words?

**Comment by philkjacobs** [comment]
Sure, that gives us a billion options - http://www.wordfind.com/3-letter-words/ is the list of 1015 3 letter scrabble-words.

**Comment by mathewantony31** [comment]
nice let's do that then. lmk if i can help in any way
